version: "3.8"

services:
  api:
    image: feedwebr-api
    ports:
      - 3000:3000
    env_file:
      - ../api/.env
    entrypoint: ["npm", "run", "start:dev"]

  website:
    image: feedwebr-website
    ports:
      - 3001:3001
    env_file:
      - .env
    entrypoint: ["npm", "run", "dev"]
